version: '3'
services: 
  app:
    container_name: calc-app
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    volumes: 
      - .:/usr/src/app
    stdin_open: true
    tty: true
